// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGvy5JsU-Fm7ohnm9HAdlbmp4k65zLsjw',
    appId: '1:158417787029:web:07d3faf2d5819ed67da39c',
    messagingSenderId: '158417787029',
    projectId: 'chatapp-920a3',
    authDomain: 'chatapp-920a3.firebaseapp.com',
    storageBucket: 'chatapp-920a3.appspot.com',
    measurementId: 'G-LP1Y1SJV6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChunr9IO8-XgZbkrStf8kg1JKVIMjdwNk',
    appId: '1:158417787029:android:2f4fb63167ba056d7da39c',
    messagingSenderId: '158417787029',
    projectId: 'chatapp-920a3',
    storageBucket: 'chatapp-920a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFKV0gWHqNMIt4TvNpVBj-qy5gbHm1YzA',
    appId: '1:158417787029:ios:60bee0e494577fde7da39c',
    messagingSenderId: '158417787029',
    projectId: 'chatapp-920a3',
    storageBucket: 'chatapp-920a3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFKV0gWHqNMIt4TvNpVBj-qy5gbHm1YzA',
    appId: '1:158417787029:ios:f196903eba6d14887da39c',
    messagingSenderId: '158417787029',
    projectId: 'chatapp-920a3',
    storageBucket: 'chatapp-920a3.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
